name: Waka Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update gist with WakaTime stats
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 0635c4927c5294110fd9f49d3adcd375
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
